"""Deterministic transitions from the externally frozen execution contract."""
from backend.models.local_llm_day import LocalLLMDayState as S

ACTIVE = frozenset({S.PREFLIGHT, S.LOADING_CONTRACT, S.INVENTORY, S.VALIDATING,
                    S.DIAGNOSING_GAP, S.COLLECTING_EVIDENCE, S.EXECUTING_DAY_WORK,
                    S.CORRECTIVE_WORK, S.REPAIR_SUPERVISOR, S.REVALIDATING})
AUTHORITY = frozenset({S.HUMAN_ACTION_REQUIRED, S.EXTERNAL_ACTION_REQUIRED})
TRANSITIONS = {
    S.IDLE: {S.PREFLIGHT},
    S.PREFLIGHT: {S.LOADING_CONTRACT, *AUTHORITY},
    S.LOADING_CONTRACT: {S.INVENTORY},
    S.INVENTORY: {S.VALIDATING},
    S.VALIDATING: {S.COMPLETE, S.DIAGNOSING_GAP},
    S.DIAGNOSING_GAP: {S.COLLECTING_EVIDENCE, S.EXECUTING_DAY_WORK, S.CORRECTIVE_WORK,
                      S.REPAIR_SUPERVISOR, S.REVALIDATING, *AUTHORITY},
    S.COLLECTING_EVIDENCE: {S.REVALIDATING, S.REPAIR_SUPERVISOR, *AUTHORITY},
    S.EXECUTING_DAY_WORK: {S.REVALIDATING, S.REPAIR_SUPERVISOR, *AUTHORITY},
    S.CORRECTIVE_WORK: {S.REVALIDATING, S.REPAIR_SUPERVISOR, *AUTHORITY},
    S.REPAIR_SUPERVISOR: {S.REVALIDATING, *AUTHORITY},
    S.REVALIDATING: {S.VALIDATING},
    S.PAUSED: {S.PREFLIGHT}, S.STOPPED: {S.PREFLIGHT},
    S.HUMAN_ACTION_REQUIRED: {S.PREFLIGHT}, S.EXTERNAL_ACTION_REQUIRED: {S.PREFLIGHT},
    S.COMPLETE: set(), S.FAILED_UNRECOVERABLE: set(),
}
for state in ACTIVE:
    TRANSITIONS[state].update({S.PAUSED, S.STOPPED, S.FAILED_UNRECOVERABLE})


def validate_transition(before: S, after: S) -> None:
    if before == after or after not in TRANSITIONS.get(before, set()):
        raise ValueError(f"STATE_MACHINE_INVARIANT:{before.value}->{after.value}")
