from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from backend.models.state import WorkflowState


class AuditEventType(str, Enum):
    TASK_STARTED = "TASK_STARTED"
    STATE_TRANSITION = "STATE_TRANSITION"
    DETERMINISTIC_CHECK = "DETERMINISTIC_CHECK"
    TRIAGE = "TRIAGE"
    CONTEXT_CREATED = "CONTEXT_CREATED"
    CODEX_RESULT = "CODEX_RESULT"
    TEST_RESULT = "TEST_RESULT"
    EVALUATION_RESULT = "EVALUATION_RESULT"
    PROGRESS_UPDATED = "PROGRESS_UPDATED"
    WORKFLOW_SKIPPED = "WORKFLOW_SKIPPED"
    SMOKE_STARTED = "SMOKE_STARTED"
    SMOKE_RESULT = "SMOKE_RESULT"
    SMOKE_ACCEPTED = "SMOKE_ACCEPTED"
    SMOKE_REJECTED = "SMOKE_REJECTED"
    TOKEN_USAGE_RECONCILED = "TOKEN_USAGE_RECONCILED"
    TOKEN_BUDGET_WARNING = "TOKEN_BUDGET_WARNING"
    DAY_PLAN_STARTED = "DAY_PLAN_STARTED"
    DAY_ARCHITECT_DECISION = "DAY_ARCHITECT_DECISION"
    DAY_MODEL_ROUTING = "DAY_MODEL_ROUTING"
    DAY_DETERMINISTIC_NO_AI = "DAY_DETERMINISTIC_NO_AI"
    DAY_TASK_RESULT = "DAY_TASK_RESULT"
    DAY_EVALUATION_RESULT = "DAY_EVALUATION_RESULT"
    DAY_HUMAN_REVIEW = "DAY_HUMAN_REVIEW"
    DAY_STOPPED = "DAY_STOPPED"
    DAY_COMPLETE = "DAY_COMPLETE"
    DAY_ESCALATION = "DAY_ESCALATION"
    DAILY_OPERATION_AUTOSTART = "DAILY_OPERATION_AUTOSTART"
    GOAL_PLAN_PROPOSED = "GOAL_PLAN_PROPOSED"
    GOAL_PLAN_REJECTED = "GOAL_PLAN_REJECTED"
    GOAL_PLAN_EXECUTED = "GOAL_PLAN_EXECUTED"
    NEXT_ACTION_CONTINUED = "NEXT_ACTION_CONTINUED"
    EXPERIMENT_RESULT = "EXPERIMENT_RESULT"
    GIT_COMPLETION_COMMITTED = "GIT_COMPLETION_COMMITTED"
    GIT_COMPLETION_PUSHED = "GIT_COMPLETION_PUSHED"
    GIT_PR_PREPARED = "GIT_PR_PREPARED"
    GIT_COMPLETION_BLOCKED = "GIT_COMPLETION_BLOCKED"
    ZERO_TOUCH_STARTED = "ZERO_TOUCH_STARTED"
    ZERO_TOUCH_COMPLETE = "ZERO_TOUCH_COMPLETE"
    ZERO_TOUCH_ATTENTION = "ZERO_TOUCH_ATTENTION"
    LOCAL_RUNTIME_PREFLIGHT = "LOCAL_RUNTIME_PREFLIGHT"
    LOCAL_RUNTIME_STARTED = "LOCAL_RUNTIME_STARTED"
    LOCAL_RUNTIME_EXTERNAL_ACTION = "LOCAL_RUNTIME_EXTERNAL_ACTION"
    WEEK1_DAY_RESULT = "WEEK1_DAY_RESULT"
    LOCAL_LLM_DAY_STARTED = "LOCAL_LLM_DAY_STARTED"
    LOCAL_LLM_DAY_COMPLETE = "LOCAL_LLM_DAY_COMPLETE"
    RETAINED_EVIDENCE_REGISTERED = "RETAINED_EVIDENCE_REGISTERED"
    AUTHORITY_BLOCKER_REPLACED_BY_REGISTERED_RETRY = "AUTHORITY_BLOCKER_REPLACED_BY_REGISTERED_RETRY"
    EXTERNAL_REVIEW_OPERATOR_RESUME = "EXTERNAL_REVIEW_OPERATOR_RESUME"
    LOCAL_LLM_CODEX_HANDOFF_READY = "LOCAL_LLM_CODEX_HANDOFF_READY"
    # Retained only to read state written by the earlier candidate-card UI.
    LOCAL_LLM_REPAIR_CARD_PENDING = "LOCAL_LLM_REPAIR_CARD_PENDING"
    LOCAL_LLM_REPAIR_CARD_VERIFIED = "LOCAL_LLM_REPAIR_CARD_VERIFIED"
    # Retained solely to read older persisted audit records; the Day Runner UI
    # intentionally exposes no scenario controls.
    SCENARIO_ACTIVATED = "SCENARIO_ACTIVATED"
    SCENARIO_RESULT = "SCENARIO_RESULT"
    LEGACY_EVENT = "LEGACY_EVENT"


class AuditEvent(BaseModel):
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    task_id: str
    event_type: AuditEventType
    message: str
    from_state: WorkflowState | None = None
    to_state: WorkflowState | None = None
    details: dict[str, Any] = Field(default_factory=dict)
